### ISSUE TITLE
Custom games & quick play screen shows SR graph

### ISSUE THREAD

**Issue by benolot** [synap5e/overtrack-web#22]
Goto the games list page as a signed in subscriber, and goto the custom games tab.

![image](https://user-images.githubusercontent.com/2461562/56617543-10e1ea00-6618-11e9-92a4-1efbeae7d757.png)

This graph doesn't need to be shown here, as there is no SR for custom games.

**Comment by benolot** [comment]
Possible discussion about whether to show win rate instead? @synap5e curious for your thoughts

**Comment by teamcoltra** [comment]
Having discussed this in #Development on Discord I think this might be the best way of presenting data for this chart. 
![image](https://user-images.githubusercontent.com/161164/56636773-a41e1e00-661e-11e9-9ad9-865d2a80cf1e.png)


That or some kind of candlestick chart, I do love candlesticks.

**Comment by benolot** [comment]
@teamcoltra what stat were you thinking of having tracked there?

**Comment by JWSenteney** [comment]
Since custom games can vary so much in what their actual purpose is, I'm not sure any chart is always going to be appropriate, especially with the new custom game workshop feature on the horizon.  Win rate is probably the only thing that makes any sense, but what does that chart even look like?  Any single game isn't going to change your win rate by much, so wouldn't it just be an extremely gradually changing chart?  KA/D is something we could chart, but is it very meaningful?

I think I'd vote to just remove it on the custom games tab.

**Comment by synap5e** [comment]
Custom game tracking is mostly intended to cater towards scrims/tournaments, hence the manual option, as most people would not find benefit in tracking custom games.
I'm not sure what this means for the display - one could argue scrim winrates don't mean much, but it could still be something people want to display. For tournaments the winrate is meaninless because who of the random nature of who is red/blue team to spectator (OT tracks the game from blue's perspective).
I would probably vote for removing the graph on customs (and quickplay), since the use case is far less defined and I feel if people want extra stats they can use a stats/winrates/etc. page for that.

**Comment by benolot** [comment]
I think removing the graph ends up being the best option. Marking issue as ready. If anyone has any other ideas, feel free to change it.

**Comment by benolot** [comment]
Same thing now needs to be applied for quick play as well as custom games screen.
